### ISSUE TITLE
slow input on terminal (buffer)

### ISSUE THREAD

**Issue by avelino** [cdr/code-server#163]
My server where the `code-server` is located in Switzerland, I'm in Brazil.
It has a certain slowness when typing in the terminal. In the editor there is no slowness.

It would be interesting to use **mosh** or have buffering in typing

[DomTerm](https://github.com/PerBothner/DomTerm) can be interesting for the `code-server`

**Comment by bjeanes** [comment]
I am running code-server on a computer on my same network and the Integrated Terminal is unusable, which is surprising. Each keystroke takes 2-3 seconds to show up, but normal editing is fine.

**Comment by kylecarbs** [comment]
If you're using safari it was a known issue that we've fixed :confetti_ball:

**Comment by bjeanes** [comment]
I'm using Chrome

**Comment by BinaryBen** [comment]
I also use Chrome and experience lag via the in browser terminal. I was going to open an issue to suggest mosh as the solution as well.

**Comment by Cosby5** [comment]
I was wondering about the same thing. I'm using chromium and have a symmetric 1gb, I still get a ridiculous lag when not on the same network.

**Comment by brandonkal** [comment]
Note that quoting your advertised bandwidth is irrelevant here. It's the latency that should be cited.

mosh support would be appreciated and very interesting.

**Comment by Cosby5** [comment]
The ping to downtown is ~20-50ms and the farthest I've ever tried to use it was there. And I can ssh straight into the same server via 2 jump host and see reasonable latency maybe a keystroke or two behind. Whereas with CodeServer even when not in terminal I'm over a word or two behind.

**Comment by sr229** [comment]
Unfortunately this is something we can't optimize at the moment. If you can replicate this at VS Online then its most probably a upstream issue - which we can't solve without patching it too much.

**Comment by brandonkal** [comment]
@Cosby5 That's tough. I've noticed even locally that VSCode's terminal is slow. That's why I prefer using iTerm for longer commands. I'm curious how many CPUs you have given code server.

**Comment by sr229** [comment]
@brandonkal the most mysterious thing is that Cloud9 had a faster terminal, so this is something on how they handled it AFAIK

**Comment by Cosby5** [comment]
@brandonkal Literally a whole machine. 4 cores and 8gigs of ram. (I wanted to be able to compile on the machine in terminal, saves setting up a build environment a half dozen times)

 Locally it's equivalent to running on the same computer, externally it's unusable. Both times it's going through Nginx.
