### ISSUE TITLE
Image files do not display

### ISSUE THREAD

**Issue by huyiqun** [cdr/code-server#4189]
## OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Manjaro
- Remote Architecture: aarch64
- `code-server --version`: 3.11.1

(I also tried browser Vivaldi on the remote machine, and safari on both mac and ipad, got the same issue.)
## Steps to Reproduce

1. Click on the image file
2.
3.

## Expected

 Display image in the opened tab

## Actual

 No image

## Logs
Both `code-server-stderr.log` and `code-server-stdout.log` are still empty even with the `--log trace` flag. Not sure why. 

Below is the browser console:

```
configuration.ts:89 Uncaught (in promise) Error: Error: your settings are undefined. Try reloading the page. If this error persists, try the troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md
    at getConfForUrl (configuration.ts:89)
    at getConf (configuration.ts:75)
    at content.ts:284
vscode.browserified.js:129 error [Service Worker] navigator is undefined
webWorkerExtensionHost.ts:117 The web worker extension host is started without an iframe sandbox!
start @ webWorkerExtensionHost.ts:117
log.ts:296   ERR Cannot read properties of undefined (reading 'replace'): TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.a [as mnemonicMenuLabel] (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:75:37234)
    at F.<anonymous> (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1921:3884)
    at n.fire (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:60:1855)
    at A.runner (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:662:6717)
    at A.doRun (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:68:17097)
    at A.onTimeout (http://192.168.1.11:8080/static/c680aae973d83583e4a73dc0c422f44021f0140e/home/pi/source/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:68:17063)
DevTools failed to load source map: Could not load content for chrome-extension://fjdmkanbdloodhegphphhklnjfngoffa/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
configuration.ts:89 Uncaught (in promise) Error: Error: your settings are undefined. Try reloading the page. If this error persists, try the troubleshooting guide: https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md
    at getConfForUrl (configuration.ts:89)
    at getConf (configuration.ts:75)
    at content.ts:284
getConfForUrl @ configuration.ts:89
getConf @ configuration.ts:75
(anonymous) @ content.ts:284
Promise.then (async)
(anonymous) @ content.ts:283
(anonymous) @ content.ts:282
(anonymous) @ content.ts:290
(anonymous) @ content.ts:290
DevTools failed to load source map: Could not load content for chrome-extension://fjdmkanbdloodhegphphhklnjfngoffa/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
main.js:211 Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.
    at main.js:211
    at new Promise (<anonymous>)
    at main.js:209
(anonymous) @ main.js:211
(anonymous) @ main.js:209
main.js:291 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at createWebviewManager (main.js:291)
    at host.js:111
createWebviewManager @ main.js:291
(anonymous) @ host.js:111
```

## Screenshot

![IMG_0016](https://user-images.githubusercontent.com/10877536/133669945-289babc6-bf07-4fee-b796-223dbf652504.jpg)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
This should be fixed in 3.12.0. Please upgrade at your latest convenience!

**Comment by huyiqun** [comment]
Thank you very much for the info! Did not realize 3.12.0 is out since I just downloaded the package days ago. After the update, I first got the `Error loading webview: Service Workers are not enabled in the browser...` error for a couple of times - I thought it was due to http, but I could not get https to work and switched back, then the error magically went away. I didn't do anything else, which is very weird.

The images are showing after the upgrade, but now the python extension won't finish loading 😭

**Comment by jsjoeio** [comment]
Weird! Well happy it's working now!

**Comment by ArtixZ** [comment]
Still have this issue at version 3.12.0.

I'm using Raspberry Pi 4 (arm32v7).

**Comment by jsjoeio** [comment]
@ArtixZ please open a new bug report or Q/A Discussion!
