### ISSUE TITLE
How to expose angular port 4200?

### ISSUE THREAD

**Issue by Disane87** [cdr/code-server#994]
First of all, thank you for this awesome project!
Now i setup the code-server to extend my dev setup and have the ability to code on my ipad. I managed to get all of it working (event with angular cli). But now I want to open the page. Angular opens a port 4200 with hot reload etc. How can I expose this port to open the page on my localhost (work machine). 

I've run the code-server v2 (latest v2) within a docker container.

**Comment by code-asher** [comment]
For now you'll have to expose the port yourself on the Docker container. Something like `-p 127.0.0.1:8081:8081`.

Tracking for having a way built into code-server to proxy ports is here: #512

**Comment by Disane87** [comment]
I've already did that but the connection is still refused. Even with curl in the container itself it's still refusing the connection.

**Comment by code-asher** [comment]
Curious. I gave it a shot but `curl localhost:4200` inside the 
container worked for me. As for accessing it outside of the 
container, keep in mind 127.0.0.1 is only available locally (so 
only within the container) which means you'll have to do something 
like `ng serve --host 0.0.0.0`.

**Comment by Disane87** [comment]
Can we reopen this to investigate it?

**Comment by Disane87** [comment]
Oh wow, today I just tested it again and now it works but nothing changed. Even the external access on the exposed port 4200 works.

**Comment by mahmoudajawad** [comment]
I'm having the same issue when trying to start `code-server` for angular development. I have published the ports in my `docker-compose.yml` file as following:
```
version: '3.3'

services:
   code-server:
     image: code-server-ng
     volumes:
       - ./project:/home/coder/project
     ports:
       - "48080:8080"
       - "14200:4200"
```

However, unlike earlier comment. I can access angular app from inside `code-server` by getting correct output for `curl localhost:4200`.

Versions info:
```
Version: 1.41.1
Commit: f51e045cd5483561afc07694f39307fb673b6d1d
Date: 2020-01-17T22:58:55.612Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 Edg/80.0.361.66
Code Server Version: 2.1698-vsc1.41.1
```

**Comment by kylecarbs** [comment]
Happy to hear you got everything working! Let us know if you have any issues :)

**Comment by lawrencetaur** [comment]
I have a similar question but not related to exposing. 

When I run ng serve, it creates a proxy urls domain.com/proxy/4200 while the index loads, the dependant files styles.css, main.js are loading from domain.com and result in a 404. Where am I going wrong? I tried changing baseurl to proxy/4200 and still doesnt work.

**Comment by code-asher** [comment]
What paths are the 404s trying to request?

If the paths are relative they might be trying to access
domain.com/proxy/styles.css so adding a trailing slash when browsing
will fix it (domain.com/proxy/4200/).

If that doesn't work trying the non-rewriting proxy might work
(domain.com/absproxy/4200/).

**Comment by shubham8550** [comment]
changing css location and " ng serve --host 0.0.0.0 --disable-host-check" fixed issues for me
